#!/bin/bash
# GPack Package Manager
# Package Manager Interface
# $Id: gpack,v 1.5 2005/06/10 10:38:42 nymacro Exp $

if ! . ./gpack.sh ; then
    echo "ERROR: Could not find GPack internals (gpack.sh)."
    exit 1
fi

ARGS=(`echo $@`)
unset ARGS[0]

case $1 in
    "build" | "bd")
	for i in "${ARGS[@]}"; do
	    pkg_build `pkg_find $i`
	done
	;;
    "install" | "in")
	for i in "${ARGS[@]}"; do
	    pkg_install `pkg_find $i`/$i*.$PKG_EXTENSION
	done
	;;
    "remove" | "rm")
	for i in "${ARGS[@]}"; do
	    pkg_remove $i
	done
	;;
    "depinst" | "di")
	for i in "${ARGS[@]}"; do
	    pkg_depinst `pkg_find $i`
	done
	
	;;
    "info" | "if")
	for i in "${ARGS[@]}"; do
	    pkg_info `pkg_find $i`
	done
	;;
    "sync" | "sy")
	echo "Syncing packages not implemented yet"
	;;
    "list")
	ls -c1 $PKG_FILE_DIR
	;;
    "installed")
	ls -c1 $PKG_CONF_DIR
	;;
    "clean")
	for i in "${ARGS[@]}"; do
	    rm `pkg_find $i`/$i*.$PKG_EXTENSION
	done
	;;
    "rebuild")
	for i in "${ARGS[@]}"; do
	    sh $0 clean $i
	    sh $0 build $i
	done
	;;
    "find")
	for i in "${ARGS[@]}"; do
	    pkg_find $i
	done
	;;
    *)
	echo "GPack $VERSION - Aaron Marks 2005"
	echo "usage:  $0 <command> <argument> [<argument>*]"
	echo "    commands:"
	echo "        build     build package"
	echo "        install   install package"
	echo "        remove    remove package"
	echo "        depinst   install package and all dependancies"
	echo "        info      print package information"
	echo "        list      list available packages"
	echo "        installed list installed packages"
	;;
esac
