#!/bin/bash
# GPack Package Manager
# Package Manager Interface
# $Id: gpack,v 1.3 2005/06/07 00:59:36 nymacro Exp $

if ! . ./gpack.sh ; then
    echo "ERROR: Could not find GPack internals (gpack.sh)."
    exit 1
fi

ARGS=(`echo $@`)
unset ARGS[0]

case $1 in
    "build" | "bd")
	for i in "${ARGS[@]}"; do
	    pkg_build $PKG_FILE_DIR/$i
	done
	;;
    "install" | "in")
	for i in "${ARGS[@]}"; do
	    pkg_install $PKG_FILE_DIR/$i/$i*.satpkg.tar.gz
	done
	;;
    "remove" | "rm")
	for i in "${ARGS[@]}"; do
	    pkg_remove $i
	done
	;;
    "depinst" | "di")
	for i in "${ARGS[@]}"; do
	    pkg_depinst $PKG_FILE_DIR/$i
	done
	
	;;
    "info" | "if")
	for i in "${ARGS[@]}"; do
	    pkg_info $PKG_FILE_DIR/$i
	done
	;;
    "sync" | "sy")
	echo "Syncing packages not implemented yet"
	;;
    "list")
	ls -c1 $PKG_FILE_DIR
	;;
    "installed")
	ls -c1 $PKG_CONF_DIR
	;;
    *)
	echo "GPack $VERSION - Aaron Marks 2005"
	echo "usage:  $0 <command> <argument> [<argument>*]"
	echo "    commands:"
	echo "        build     build package"
	echo "        install   install package"
	echo "        remove    remove package"
	echo "        depinst   install package and all dependancies"
	echo "        info      print package information"
	echo "        list      list available packages"
	echo "        installed list installed packages"
	;;
esac
